[theme]
base = "dark"
primaryColor = "#e8e4d6"
backgroundColor = "#07090c"
secondaryBackgroundColor = "#0d1015"
textColor = "#e8e4d6"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = false
